# Generated by Django 2.1.2 on 2019-01-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181027_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('director', models.CharField(max_length=30)),
                ('rating', models.PositiveIntegerField()),
                ('year', models.DateField()),
            ],
        ),
    ]
